import { describe, expect, it } from "vitest"
import { catalog } from "../catalog"
import type { Plan, Profile, PlanIntent, PriorityId } from "../types"
import { getProfileErrors } from "./capabilities"
import { exportObject } from "./export"
import { parseImportedPlan } from "./persistence"
import { getRecommendedSettings } from "./recommendations"
// Raw-text import (a Vite/vitest feature declared by the "vite/client" types
// already used across this project) avoids depending on Node's `fs` types,
// which are intentionally excluded from the browser app's tsconfig.
import fixtureContents from "../../tooling/se-results-interpreter/fixtures/synthetic-export.json?raw"

/**
 * `tooling/se-results-interpreter/fixtures/synthetic-export.json` backs the
 * SE results interpretation agent's documentation and static contract
 * checks (see docs/se-results-interpretation.md and
 * tooling/se-results-interpreter/test/). It must be a genuinely valid,
 * current export — not merely schema-shaped — so this suite proves it by:
 *   1. Running it through the same canonical import path the configurator
 *      uses for plan re-entry.
 *   2. Confirming its profile has zero compatibility errors under the live
 *      capability model (catches invalid deployment/account/license
 *      combinations that per-field enum checks alone would miss).
 *   3. Cross-checking every referenced setting ID against the live catalog.
 *   4. Reconstructing the plan the fixture claims to represent (its own
 *      `profile`, `intent`, `priorities`, explicit selections, and reviewed
 *      IDs) and recomputing the export with this repository's own
 *      recommendation and export logic, then diffing the result against the
 *      checked-in fixture — proof the file is exactly what the app produces
 *      today for that plan, not hand-written.
 */
const fixture = JSON.parse(fixtureContents) as {
  schema: { name: string; version: number }
  schemaVersion: number
  generatedAt: string
  profile: Profile
  intent: PlanIntent
  priorities: PriorityId[]
  reviewedSettingIds: string[]
  settings: { id: string; selected: string; selectionSource: string }[]
  excludedDecisions: { id: string }[]
}

describe("SE results interpreter synthetic fixture", () => {
  it("is accepted by the configurator's own import/parser validation path", () => {
    const result = parseImportedPlan(fixtureContents)
    expect(result.ok).toBe(true)
  })

  it("declares the current desired-state schema", () => {
    expect(fixture.schema.name).toBe("github-enterprise-settings-configurator.desired-state")
    expect(fixture.schema.version).toBe(2)
    expect(fixture.schemaVersion).toBe(2)
  })

  it("has a profile with zero capability/compatibility errors", () => {
    // Catches an impossible combination — such as GHES + managed users + a
    // Copilot license — that per-field enum validation alone would miss.
    expect(getProfileErrors(fixture.profile)).toEqual([])
  })

  it("references only real, current catalog setting IDs", () => {
    const catalogIds = new Set(catalog.map((setting) => setting.id))
    for (const setting of fixture.settings) {
      expect(catalogIds.has(setting.id), `unknown catalog setting id: ${setting.id}`).toBe(true)
    }
    for (const excluded of fixture.excludedDecisions) {
      expect(catalogIds.has(excluded.id), `unknown catalog setting id: ${excluded.id}`).toBe(true)
    }
  })

  it("is regenerated byte-for-byte by this repository's own recommendation and export logic", () => {
    const explicitSelections = Object.fromEntries(
      fixture.settings
        .filter((setting) => setting.selectionSource === "explicit-selection")
        .map((setting) => [setting.id, setting.selected]),
    )
    const plan: Plan = {
      profile: fixture.profile,
      intent: fixture.intent,
      priorities: fixture.priorities,
      selections: explicitSelections,
    }
    const settings = getRecommendedSettings(plan)
    const recomputed = exportObject(plan, settings, fixture.reviewedSettingIds)
    // generatedAt is intentionally frozen in the checked-in fixture for
    // reproducibility; align it before comparing everything else.
    recomputed.generatedAt = fixture.generatedAt

    expect(JSON.parse(JSON.stringify(recomputed))).toEqual(JSON.parse(fixtureContents))
  })
})
