import type { PriorityId, Setting, Source } from "./types"

export const priorityOptions: { id: PriorityId; label: string; description: string }[] = [
  { id: "secure-ghec", label: "Secure GHEC baseline", description: "A practical enterprise guardrail set." },
  { id: "emu-entra", label: "EMU + Entra", description: "Managed identities and lifecycle controls." },
  { id: "regulated-overlay", label: "Regulated overlay", description: "Evidence, ownership, and tighter change paths." },
  { id: "copilot-cost", label: "Copilot cost-controlled", description: "Allocation, budget, and usage guardrails." },
  { id: "security-rollout", label: "Code-security rollout", description: "Incremental coverage with clear ownership." },
  { id: "migration-ready", label: "Migration readiness", description: "Sequencing and reversible control changes." },
]

const docs = (label: string, url: string): Source => ({
  label,
  tier: "GitHub Docs · mechanics",
  url,
})

const wa: Source = {
  label: "GitHub Well-Architected",
  tier: "Well-Architected · principles",
  url: "https://learn.github.com/well-architected/",
}

const safeSettings: Source = {
  label: "safe-settings",
  tier: "Worked example · adaptable",
  url: "https://github.com/github-community-projects/safe-settings",
}

const recipes: Source = {
  label: "ruleset-recipes",
  tier: "Worked example · adaptable",
  url: "https://github.com/github/ruleset-recipes",
}

const copilotAdoption: Source = {
  label: "Copilot adoption guide",
  tier: "Worked example · adaptable",
  url: "https://samqbush.github.io/copilot-adoption/",
}

const copilotCost: Source = {
  label: "Copilot cost management",
  tier: "Worked example · adaptable",
  url: "https://samqbush.github.io/copilot-adoption/cost-management/",
}

const terraform: Source = {
  label: "Terraform provider for GitHub",
  tier: "Automation adapter · execution",
  url: "https://github.com/integrations/terraform-provider-github",
}

export const catalog: Setting[] = [
  // --- Identity & administration -------------------------------------------------
  {
    id: "enterprise-type",
    domain: "Identity & administration",
    title: "Enterprise type and hosting consequence",
    prompt: "Make the hosting decision explicit in the desired state.",
    choices: [
      { id: "dotcom", label: "GitHub Enterprise Cloud", description: "Standard GitHub.com enterprise tenancy." },
      { id: "residency", label: "GHE.com data residency", description: "Regional residency and separate hostname." },
      { id: "ghes", label: "GHES 3.21", description: "Self-hosted appliance operations and upgrade ownership." },
    ],
    recommended: "dotcom",
    editable: false,
    rationale: "Hosting defines identity, networking, operational ownership, and feature availability.",
    tradeoff: "Data residency and self-hosting add operational constraints in exchange for control.",
    prerequisites: "A named enterprise owner and an approved hostname or appliance plan.",
    consequences: "Changing hosting later is a migration program, not a toggle.",
    scope: "Enterprise",
    role: "Enterprise owner",
    applyMethod: "Enterprise setup and documented architecture decision",
    influence: "Guardrail",
    postureWeight: 0,
    effortByChoice: { dotcom: 0.3, residency: 0.65, ghes: 1 },
    rolloutBand: "High",
    ongoingBand: "Moderate",
    sources: [docs("Enterprise account overview", "https://docs.github.com/en/enterprise-cloud@latest/admin/overview/about-github-enterprise-cloud"), wa],
  },
  {
    id: "identity-lifecycle",
    domain: "Identity & administration",
    title: "Identity, SSO, and provisioning lifecycle",
    prompt: "Confirm the identity lifecycle that matches the deployment and account model already captured in the profile.",
    choices: [
      {
        id: "personal-access-scim",
        label: "Personal accounts · SAML SSO + access-only SCIM",
        description: "Centralized sign-in; SCIM is limited to granting and revoking enterprise access for personal accounts.",
        availability: { allOf: ["personal-accounts", "enterprise-saml", "scim-access"] },
      },
      {
        id: "personal-saml",
        label: "Personal accounts · SAML SSO only",
        description: "Centralized sign-in; enterprise membership and removal stay a manual process.",
        availability: { allOf: ["personal-accounts", "enterprise-saml"], noneOf: ["scim-access"] },
      },
      {
        id: "personal-github",
        label: "Personal accounts · GitHub-managed sign-in",
        description: "No enterprise-level SSO; members sign in with their individual GitHub accounts.",
        availability: { allOf: ["personal-accounts"], noneOf: ["enterprise-saml", "oidc", "scim-access"] },
      },
      {
        id: "emu-saml-scim",
        label: "Enterprise Managed Users · SAML SSO + required SCIM",
        description: "Every account is provisioned, updated, and deprovisioned by the identity provider.",
        availability: { allOf: ["managed-users", "enterprise-saml", "scim"] },
      },
      {
        id: "emu-oidc-scim",
        label: "Enterprise Managed Users · OIDC + required SCIM",
        description: "OIDC sign-in paired with mandatory SCIM lifecycle management.",
        availability: { allOf: ["managed-users", "oidc", "scim"] },
      },
      {
        id: "ghes-built-in",
        label: "GHES · Built-in authentication, manual lifecycle",
        description: "Local GHES accounts with administrator-managed onboarding and offboarding.",
        availability: {
          allOf: ["instance-accounts", "built-in-authentication", "manual-provisioning"],
        },
      },
      {
        id: "ghes-saml-jit",
        label: "GHES · SAML SSO + just-in-time provisioning",
        description: "Accounts are created automatically on first SAML sign-in; removal stays manual.",
        availability: { allOf: ["instance-accounts", "enterprise-saml", "jit-provisioning"] },
      },
      {
        id: "ghes-saml-scim-preview",
        label: "GHES · SAML SSO + SCIM (public preview)",
        description: "Automated lifecycle using the GHES 3.21 SCIM public preview; SAML authentication is required.",
        availability: { allOf: ["instance-accounts", "enterprise-saml", "scim", "ghes-scim-preview"] },
      },
      {
        id: "ghes-ldap",
        label: "GHES · LDAP-synchronized lifecycle",
        description: "Accounts and group membership stay synchronized from the directory.",
        availability: { allOf: ["instance-accounts", "ldap-lifecycle"] },
      },
      {
        id: "ghes-cas",
        label: "GHES · CAS with first-sign-in provisioning",
        description: "CAS authenticates members; GHES creates the account on first sign-in rather than through JIT SAML provisioning.",
        availability: {
          allOf: ["instance-accounts", "cas-authentication", "first-sign-in-provisioning"],
        },
      },
    ],
    recommended: "personal-github",
    editable: false,
    rationale: "The identity lifecycle is fixed by the deployment, account model, and directory choice already captured in the profile.",
    tradeoff: "Changing lifecycle later means re-provisioning identities and re-testing SSO end to end.",
    prerequisites: "A confirmed account model, authentication method, and provisioning method for this deployment.",
    consequences: "Recording the wrong lifecycle here misrepresents onboarding, offboarding, and audit evidence.",
    scope: "Enterprise identity",
    role: "Identity administrator",
    applyMethod: "Enterprise or organization identity provider configuration",
    influence: "Guardrail",
    postureWeight: 0,
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [
      docs("SAML SSO for enterprise", "https://docs.github.com/en/enterprise-cloud@latest/admin/managing-iam/using-saml-for-enterprise-iam/configuring-saml-single-sign-on-for-your-enterprise"),
      docs("SCIM provisioning", "https://docs.github.com/en/enterprise-cloud@latest/admin/managing-iam/provisioning-user-accounts-with-scim/configuring-scim-provisioning-for-users"),
      docs("Enterprise Managed Users", "https://docs.github.com/en/enterprise-cloud@latest/admin/concepts/identity-and-access-management/enterprise-managed-users"),
      docs("Using CAS for GHES", "https://docs.github.com/en/enterprise-server@3.21/admin/managing-iam/using-cas-for-enterprise-iam/using-cas"),
      docs("Using LDAP for GHES", "https://docs.github.com/en/enterprise-server@3.21/admin/managing-iam/using-ldap-for-enterprise-iam/using-ldap"),
      docs("SCIM provisioning on GHES (public preview)", "https://docs.github.com/en/enterprise-server@3.21/admin/managing-iam/provisioning-user-accounts-with-scim/user-provisioning-with-scim-on-ghes"),
    ],
  },
  {
    id: "admin-redundancy",
    domain: "Identity & administration",
    title: "Enterprise admin redundancy",
    prompt: "Set the operational minimum for accountable enterprise owners.",
    choices: [
      { id: "three", label: "At least 3 named owners", description: "Redundant coverage across time zones or teams." },
      { id: "two", label: "At least 2 named owners", description: "Minimum resilience with limited coverage." },
      { id: "one", label: "Single owner", description: "Temporary only; creates a continuity risk." },
    ],
    recommended: "three",
    availability: { allOf: ["enterprise-account"] },
    rationale: "Multiple accountable owners reduce a single-person recovery failure.",
    tradeoff: "More owners require clearer role boundaries and audit attention.",
    prerequisites: "Named individuals, an escalation route, and periodic access review.",
    consequences: "A single owner can block incident recovery or renewal administration.",
    scope: "Enterprise",
    role: "Enterprise owner",
    applyMethod: "Access assignment and operating runbook",
    influence: "Protective",
    rolloutBand: "Low",
    ongoingBand: "Low",
    sources: [wa, docs("Managing enterprise members", "https://docs.github.com/en/enterprise-cloud@latest/admin/user-management/managing-users-in-your-enterprise")],
  },
  {
    id: "verified-domains",
    domain: "Identity & administration",
    title: "Verified domain ownership",
    prompt: "Choose the domain verification control for enterprise identity.",
    choices: [
      { id: "verify", label: "Verify and monitor domains", description: "Establish organizational control of company domains." },
      { id: "verify-migration", label: "Verify in migration wave", description: "Sequence verification with identity cutover." },
      { id: "defer", label: "Defer with owner", description: "Track as a time-bound dependency." },
    ],
    recommended: "verify",
    availability: { allOf: ["enterprise-account"] },
    rationale: "Verified domains anchor identity and notification governance to an accountable organization.",
    tradeoff: "DNS changes need coordination and a clear rollback owner.",
    prerequisites: "DNS access and an inventory of active corporate domains.",
    consequences: "Unverified domains can complicate identity governance and support workflows.",
    scope: "Enterprise",
    role: "Domain administrator",
    applyMethod: "Enterprise settings and DNS TXT record",
    influence: "Guardrail",
    rolloutBand: "Low",
    ongoingBand: "Low",
    sources: [docs("Verifying domains", "https://docs.github.com/en/enterprise-cloud@latest/admin/configuring-settings/configuring-user-applications-for-your-enterprise/verifying-or-approving-a-domain-for-your-enterprise")],
  },

  // --- Organization & repository governance ---------------------------------------
  {
    id: "default-repo-permission",
    domain: "Organization & repository governance",
    title: "Default repository permission",
    prompt: "Set the access level given to organization members by default.",
    choices: [
      { id: "none", label: "No default access", description: "Teams grant repository access intentionally." },
      { id: "read", label: "Read by default", description: "Members can discover internal repositories." },
      { id: "write", label: "Write by default", description: "Broad collaboration with a wider change surface." },
    ],
    recommended: "none",
    availability: { allOf: ["enterprise-account"] },
    rationale: "Intentional repository access reduces accidental exposure and simplifies access review.",
    tradeoff: "Teams must be maintained and onboarding can take an extra request.",
    prerequisites: "A team model and a repository ownership convention.",
    consequences: "Default access can make private repository visibility broader than intended.",
    scope: "Organization",
    role: "Organization owner",
    applyMethod: "Organization member privileges",
    influence: "Protective",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Organization member privileges", "https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/setting-base-permissions-for-an-organization"), safeSettings],
  },
  {
    id: "member-repo-creation",
    domain: "Organization & repository governance",
    title: "Member repository creation",
    prompt: "Choose how new repository creation is governed.",
    choices: [
      { id: "restricted", label: "Restricted to owners", description: "Use a request or template-led creation path." },
      { id: "private-only", label: "Members can create private repos", description: "Balanced autonomy with a private default." },
      { id: "open", label: "Members can create all repo types", description: "Maximum autonomy; requires broad education." },
    ],
    recommended: "private-only",
    availability: { allOf: ["enterprise-account"] },
    rationale: "A controlled creation path helps establish ownership, templates, and baseline controls early.",
    tradeoff: "Tighter controls can slow experimentation without a lightweight request path.",
    prerequisites: "Repository templates and an ownership intake path.",
    consequences: "Open creation can yield unmanaged repositories and uneven policy adoption.",
    scope: "Organization",
    role: "Organization owner",
    applyMethod: "Organization member privileges",
    influence: "Guardrail",
    rolloutBand: "Moderate",
    ongoingBand: "Low",
    sources: [docs("Restricting repository creation", "https://docs.github.com/en/organizations/managing-organization-settings/restricting-repository-creation-in-your-organization"), safeSettings],
  },
  {
    id: "default-branch-ruleset",
    domain: "Organization & repository governance",
    title: "Default branch ruleset",
    prompt: "Set the default protection path for production branches.",
    choices: [
      { id: "required-pr", label: "Required PR + checks", description: "Require review and validated checks before merge." },
      { id: "pr-only", label: "Required pull request", description: "Require review; checks are introduced later." },
      { id: "advisory", label: "Template only", description: "Offer an adaptable ruleset without enforcement." },
    ],
    recommended: "required-pr",
    availability: { allOf: ["enterprise-account"] },
    rationale: "A default ruleset gives new repositories an intentional merge control from creation.",
    tradeoff: "Required checks need reliable CI ownership or they become delivery friction.",
    prerequisites: "Named code owners, reliable checks, and an exception process.",
    consequences: "Overly broad enforcement can block emergency changes without bypass governance.",
    scope: "Organization and repositories",
    role: "Organization owner / repository administrator",
    applyMethod: "Repository rulesets or policy-as-code adapter",
    influence: "Protective",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("About rulesets", "https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets"), recipes, terraform],
  },
  {
    id: "outside-collaborators",
    domain: "Organization & repository governance",
    title: "Outside collaborator and forking posture",
    prompt: "Set the collaboration boundary for repositories with sensitive code.",
    choices: [
      { id: "approve-no-private-forks", label: "Approval + no private forks", description: "Require review before external access or private forking." },
      { id: "approve-limited-forks", label: "Approval + limited forks", description: "Allow exceptions for approved partner workflows." },
      { id: "open", label: "Organization discretion", description: "Individual repositories decide without a shared baseline." },
    ],
    recommended: "approve-no-private-forks",
    availability: { allOf: ["enterprise-account"] },
    rationale: "External collaboration is a separate access and data-flow decision from membership.",
    tradeoff: "Partner work needs a clear exception and review path.",
    prerequisites: "Repository classification and an external collaborator approval owner.",
    consequences: "Unbounded forks can widen where source and secrets may be copied.",
    scope: "Organization",
    role: "Organization owner",
    applyMethod: "Organization member, fork, and collaborator settings",
    influence: "Protective",
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Managing outside collaborators", "https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-outside-collaborators"), safeSettings],
  },

  // --- Code security ---------------------------------------------------------------
  {
    id: "secret-protection-configuration",
    domain: "Code security",
    title: "Secret Protection configuration coverage",
    prompt: "Choose how Secret Protection scanning and push protection are rolled out.",
    choices: [
      { id: "baseline-all", label: "Baseline on all eligible repos", description: "Apply a standard configuration with exceptions tracked." },
      { id: "wave", label: "Risk-based rollout waves", description: "Start with critical repositories and expand." },
      { id: "opt-in", label: "Repository opt-in", description: "Teams enable features independently." },
    ],
    recommended: "wave",
    availability: { anyOf: ["secret-scanning"] },
    rationale: "A visible coverage plan makes Secret Protection rollout ownership and exceptions explicit, independent of Code Security.",
    tradeoff: "Broad defaults create alert and remediation demand that must be staffed.",
    prerequisites: "Repository inventory, service ownership, and a triage operating model.",
    consequences: "Opt-in delivery can leave critical repositories without expected secret-scanning coverage.",
    scope: "Enterprise or organization",
    role: "Security manager / organization owner",
    applyMethod: "Security configurations and rollout tracking",
    influence: "Protective",
    foundational: true,
    rolloutBand: "High",
    ongoingBand: "High",
    sources: [docs("Security configurations", "https://docs.github.com/en/code-security/how-tos/secure-at-scale/configure-organization-security/establish-complete-coverage/apply-custom-configuration"), wa],
  },
  {
    id: "secret-scanning-push-protection",
    domain: "Code security",
    title: "Secret scanning and push protection",
    prompt: "Set the secret exposure prevention posture.",
    choices: [
      { id: "scan-push", label: "Scanning + push protection", description: "Detect secrets and block likely accidental commits." },
      { id: "scan-only", label: "Scanning only", description: "Detect after commit; retain developer remediation path." },
      { id: "pilot", label: "Pilot in sensitive repositories", description: "Test bypass and remediation support before scale." },
    ],
    recommended: "scan-push",
    availability: { anyOf: ["secret-scanning"] },
    rationale: "Preventing likely secrets at commit time reduces downstream exposure response work.",
    tradeoff: "Developers need a documented bypass and false-positive support route.",
    prerequisites: "Secret response owner, developer communication, and bypass audit review.",
    consequences: "Scan-only detects a secret after it may already be in history.",
    scope: "Organization and repositories",
    role: "Security manager",
    applyMethod: "Code security settings and security configuration",
    influence: "Protective",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Push protection", "https://docs.github.com/en/code-security/how-tos/secure-your-secrets/work-with-leak-prevention/push-protection-on-the-command-line"), wa],
  },
  {
    id: "code-security-configuration",
    domain: "Code security",
    title: "Code Security configuration coverage",
    prompt: "Choose how Code Security scanning defaults are rolled out.",
    choices: [
      { id: "baseline-all", label: "Baseline on all eligible repos", description: "Apply a standard configuration with exceptions tracked." },
      { id: "wave", label: "Risk-based rollout waves", description: "Start with critical repositories and expand." },
      { id: "opt-in", label: "Repository opt-in", description: "Teams enable features independently." },
    ],
    recommended: "wave",
    availability: { anyOf: ["code-scanning"] },
    rationale: "A visible coverage plan makes Code Security rollout ownership and exceptions explicit, independent of Secret Protection.",
    tradeoff: "Broad defaults create alert and remediation demand that must be staffed.",
    prerequisites: "Repository inventory, service ownership, and a triage operating model.",
    consequences: "Opt-in delivery can leave critical repositories without expected code-scanning coverage.",
    scope: "Enterprise or organization",
    role: "Security manager / organization owner",
    applyMethod: "Security configurations and rollout tracking",
    influence: "Protective",
    foundational: true,
    rolloutBand: "High",
    ongoingBand: "High",
    sources: [docs("Security configurations", "https://docs.github.com/en/code-security/how-tos/secure-at-scale/configure-organization-security/establish-complete-coverage/apply-custom-configuration"), wa],
  },
  {
    id: "code-scanning-setup",
    domain: "Code security",
    title: "Code scanning default setup",
    prompt: "Choose how CodeQL default setup is applied across repositories.",
    choices: [
      { id: "default-setup-all", label: "Default setup on all eligible repos", description: "Enable CodeQL default setup broadly with exceptions tracked." },
      { id: "default-setup-wave", label: "Default setup in priority waves", description: "Sequence default setup by repository risk or ownership readiness." },
      { id: "advanced-only", label: "Advanced/custom setup only", description: "Rely on repository-authored workflows instead of default setup." },
    ],
    recommended: "default-setup-all",
    availability: { anyOf: ["code-scanning"] },
    rationale: "Default setup gives repositories working CodeQL analysis without hand-authored workflow maintenance.",
    tradeoff: "Advanced setup is sometimes required for custom build steps or non-default languages.",
    prerequisites: "Supported language inventory and a triage path for new findings.",
    consequences: "Advanced-only setup can leave repositories without scanning until a workflow is authored.",
    scope: "Organization and repositories",
    role: "Security manager / repository administrator",
    applyMethod: "Code scanning default setup at scale",
    influence: "Protective",
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Configuring default setup for code scanning at scale", "https://docs.github.com/en/code-security/how-tos/secure-at-scale/configure-organization-security/configure-specific-tools/code-scanning-at-scale")],
  },
  {
    id: "dependency-coverage",
    domain: "Code security",
    title: "Dependency graph and Dependabot",
    prompt: "Set dependency visibility and update expectations.",
    choices: [
      { id: "graph-alerts-updates", label: "Graph + alerts + updates", description: "Establish discovery and managed update cadence." },
      { id: "graph-alerts", label: "Graph + alerts", description: "Visibility first; teams manage updates manually." },
      { id: "graph-only", label: "Dependency graph only", description: "Inventory without a shared remediation signal." },
    ],
    recommended: "graph-alerts-updates",
    availability: { allOf: ["dependency-graph", "dependabot-alerts"] },
    rationale: "Dependency visibility without ownership and updates yields an unmanaged alert backlog. This baseline stays available regardless of paid Secret Protection or Code Security licensing.",
    tradeoff: "Automated updates require CI health and dependable ownership.",
    prerequisites: "Dependency owners, tested CI, and severity routing.",
    consequences: "Unmanaged Dependabot alerts can become noisy and lose urgency.",
    scope: "Organization and repositories",
    role: "Security manager / repository administrator",
    applyMethod: "Code security and repository Dependabot settings",
    influence: "Protective",
    rolloutBand: "Moderate",
    ongoingBand: "High",
    sources: [docs("Dependabot alerts", "https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts"), docs("Dependabot version updates", "https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates")],
  },
  {
    id: "premium-dependabot",
    domain: "Code security",
    title: "Premium Dependabot triage and autofix",
    prompt: "Choose how Code Security's premium Dependabot capabilities are governed.",
    choices: [
      { id: "auto-triage-managed", label: "Managed auto-triage rules + reviewed exceptions", description: "Curate custom auto-triage rules with a periodic exception review." },
      { id: "auto-triage-presets", label: "GitHub preset auto-triage rules only", description: "Use GitHub-curated presets without custom rules." },
      { id: "manual-triage", label: "Manual triage only", description: "Review every Dependabot alert without automated dismissal." },
    ],
    recommended: "auto-triage-presets",
    availability: { allOf: ["code-security"] },
    rationale: "Auto-triage rules reduce alert noise, but require ownership so exceptions do not hide real risk.",
    tradeoff: "Custom rules need periodic review or they can mask newly relevant alerts.",
    prerequisites: "A licensed Code Security configuration and a named Dependabot alert owner.",
    consequences: "Manual-only triage does not scale once dependency alert volume grows.",
    scope: "Organization and repositories",
    role: "Security manager",
    applyMethod: "Dependabot auto-triage rules",
    influence: "Enabling",
    rolloutBand: "Low",
    ongoingBand: "Moderate",
    sources: [docs("Dependabot auto-triage rules", "https://docs.github.com/en/code-security/concepts/supply-chain-security/dependabot-auto-triage-rules"), docs("Customizing auto-triage rules", "https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/manage-your-dependency-security/auto-triage-dependabot-alerts")],
  },

  // --- Code quality ------------------------------------------------------------------
  {
    id: "code-quality-targeting",
    domain: "Code quality",
    title: "Code Quality targeting",
    prompt: "Choose which repositories GitHub Code Quality analyzes first.",
    choices: [
      { id: "all-eligible", label: "Target all eligible repositories", description: "Enable Code Quality broadly with exceptions tracked." },
      { id: "priority-repos", label: "Target priority repositories first", description: "Start with actively developed or customer-facing repositories." },
      { id: "pilot", label: "Pilot in a small set of repositories", description: "Validate signal quality before broader targeting." },
    ],
    recommended: "priority-repos",
    availability: { allOf: ["code-quality"] },
    rationale: "Targeting scope determines how quickly Code Quality findings become representative of the codebase.",
    tradeoff: "Broad targeting surfaces more findings before teams have triage capacity.",
    prerequisites: "A repository inventory and an owner for each targeted repository.",
    consequences: "Pilot-only targeting can delay organization-wide quality visibility.",
    scope: "Organization and repositories",
    role: "Engineering manager / repository administrator",
    applyMethod: "Code Quality repository targeting",
    influence: "Enabling",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Low",
    sources: [docs("Enabling GitHub Code Quality", "https://docs.github.com/en/code-security/how-tos/maintain-quality-code/enable-code-quality")],
  },
  {
    id: "code-quality-setup-findings",
    domain: "Code quality",
    title: "Code Quality setup and findings triage",
    prompt: "Choose how Code Quality is enabled and how findings are reviewed.",
    choices: [
      { id: "enabled-triage", label: "Enable Code Quality + triage findings on a cadence", description: "Establish a recurring review of new findings." },
      { id: "enabled-ad-hoc", label: "Enable Code Quality; findings reviewed ad hoc", description: "Enable analysis without a scheduled review cadence." },
      { id: "explore-only", label: "Explore findings before enabling broadly", description: "Review the organization dashboard before turning on scans." },
    ],
    recommended: "enabled-triage",
    availability: { allOf: ["code-quality"] },
    rationale: "A triage cadence turns Code Quality findings into fixed backlog items instead of an ignored list.",
    tradeoff: "A recurring cadence needs a named owner and calendar time.",
    prerequisites: "An organization-level findings dashboard reviewer.",
    consequences: "Ad hoc review can let findings accumulate without resolution.",
    scope: "Organization and repositories",
    role: "Engineering manager",
    applyMethod: "Code Quality enablement and findings dashboard",
    influence: "Enabling",
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Enabling GitHub Code Quality", "https://docs.github.com/en/code-security/how-tos/maintain-quality-code/enable-code-quality"), docs("Exploring Code Quality results", "https://docs.github.com/en/code-security/how-tos/maintain-quality-code/explore-code-quality"), docs("Fixing code quality findings in your backlog", "https://docs.github.com/en/code-security/how-tos/maintain-quality-code/fix-backlog-findings")],
  },
  {
    id: "code-quality-coverage",
    domain: "Code quality",
    title: "Code Quality coverage rollout",
    prompt: "Choose the rollout pace for Code Quality coverage across the organization.",
    choices: [
      { id: "baseline-all", label: "Baseline on all eligible repos", description: "Apply Code Quality broadly with exceptions tracked." },
      { id: "wave", label: "Risk-based rollout waves", description: "Expand coverage by repository priority over time." },
      { id: "opt-in", label: "Repository opt-in", description: "Teams enable Code Quality independently." },
    ],
    recommended: "wave",
    availability: { allOf: ["code-quality"] },
    rationale: "A visible coverage plan keeps Code Quality rollout ownership and exceptions explicit.",
    tradeoff: "Broad coverage creates a findings-triage workload that must be staffed.",
    prerequisites: "Repository inventory and a coverage tracking owner.",
    consequences: "Opt-in delivery can leave key repositories without quality visibility.",
    scope: "Organization and repositories",
    role: "Engineering manager / organization owner",
    applyMethod: "Code Quality enablement and rollout tracking",
    influence: "Enabling",
    rolloutBand: "High",
    ongoingBand: "Moderate",
    sources: [docs("Enabling GitHub Code Quality", "https://docs.github.com/en/code-security/how-tos/maintain-quality-code/enable-code-quality")],
  },
  {
    id: "code-quality-merge-gates",
    domain: "Code quality",
    title: "Code Quality merge gate policy",
    prompt: "Choose whether Code Quality findings can block a pull request merge.",
    choices: [
      { id: "required-gate", label: "Findings block merge until resolved", description: "Enforce quality thresholds as a required check." },
      { id: "advisory-gate", label: "Findings surfaced; merge allowed with override", description: "Show findings without blocking; owners can override." },
      { id: "no-gate", label: "Informational only; no merge gate", description: "Findings are visible but never affect mergeability." },
    ],
    recommended: "advisory-gate",
    availability: { allOf: ["code-quality"] },
    rationale: "Merge gates decide whether Code Quality is advisory or an enforced quality bar for changes.",
    tradeoff: "Required gates need reliable, low-noise findings or they become delivery friction.",
    prerequisites: "A tuned threshold and an owner for gate exceptions.",
    consequences: "No gate can leave quality regressions unaddressed indefinitely.",
    scope: "Organization and repositories",
    role: "Engineering manager / repository administrator",
    applyMethod: "Code Quality pull request thresholds",
    influence: "Guardrail",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Low",
    sources: [docs("Setting code quality thresholds for pull requests", "https://docs.github.com/en/code-security/how-tos/maintain-quality-code/set-pr-thresholds")],
  },

  // --- Actions & supply chain ---------------------------------------------------------
  {
    id: "allowed-actions",
    domain: "Actions & supply chain",
    title: "Allowed Actions policy",
    prompt: "Choose the supply-chain boundary for workflow actions.",
    choices: [
      { id: "verified-pinned", label: "Verified creators + SHA pinning", description: "Allow a curated set with immutable action references." },
      { id: "verified", label: "Verified creators", description: "Trust a publisher set without pin enforcement." },
      { id: "all", label: "All Marketplace actions", description: "Repository teams select dependencies freely." },
    ],
    recommended: "verified-pinned",
    availability: { allOf: ["actions", "actions-planning"] },
    rationale: "Workflow actions are executable third-party dependencies and need a deliberate trust boundary.",
    tradeoff: "Pinning and curation create maintenance work for platform teams.",
    prerequisites: "An approved action catalog and update process.",
    consequences: "Open policy broadens the dependency attack surface of CI workloads.",
    scope: "Enterprise or organization",
    role: "Actions administrator",
    applyMethod: "Actions policy and policy-as-code adapter",
    influence: "Protective",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Allowed actions", "https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization"), wa],
  },
  {
    id: "workflow-token",
    domain: "Actions & supply chain",
    title: "Workflow token default",
    prompt: "Set the default permission level for GITHUB_TOKEN.",
    choices: [
      { id: "read", label: "Read-only by default", description: "Workflows elevate only the permissions they need." },
      { id: "migration", label: "Read-only with migration exceptions", description: "Track temporary workflow exceptions explicitly." },
      { id: "write", label: "Read/write by default", description: "Convenient legacy behavior with broader capability." },
    ],
    recommended: "read",
    availability: { allOf: ["actions", "actions-planning"] },
    rationale: "Least-privilege workflow defaults limit the blast radius of compromised workflow code.",
    tradeoff: "Existing workflows may need explicit permission declarations.",
    prerequisites: "A workflow inventory and validation in representative repositories.",
    consequences: "Changing the default can break releases if not piloted.",
    scope: "Enterprise, organization, repository",
    role: "Actions administrator / repository maintainer",
    applyMethod: "Actions settings and workflow YAML changes",
    influence: "Protective",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Low",
    sources: [docs("Automatic token authentication", "https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication"), wa],
  },
  {
    id: "runner-network",
    domain: "Actions & supply chain",
    title: "Runner and network boundary",
    prompt: "Choose where sensitive workflows can run.",
    choices: [
      { id: "segmented", label: "Segmented runners + controlled egress", description: "Separate trust zones and define network policy." },
      { id: "hosted", label: "GitHub-hosted runners", description: "Default managed runner model for standard workloads." },
      { id: "self-hosted", label: "Self-hosted by exception", description: "Use only with an owner and isolation design." },
    ],
    recommended: "hosted",
    availability: { allOf: ["actions", "actions-planning"] },
    rationale: "Runner choice is a workload trust-boundary decision, not only a capacity decision.",
    tradeoff: "Self-hosted runners enable private connectivity but demand patching and isolation ownership.",
    prerequisites: "Workload classification, network owner, and runner lifecycle plan.",
    consequences: "Shared self-hosted runners can expose credentials or network paths across workloads.",
    scope: "Enterprise and organization",
    role: "Actions administrator / infrastructure owner",
    applyMethod: "Runner groups, network design, and enterprise Actions settings",
    influence: "Guardrail",
    rolloutBand: "High",
    ongoingBand: "High",
    sources: [docs("Self-hosted runners", "https://docs.github.com/en/actions/concepts/runners/self-hosted-runners"), wa],
  },

  // --- Audit visibility ------------------------------------------------------------
  {
    id: "audit-streaming",
    domain: "Audit visibility",
    title: "Audit retention and streaming",
    prompt: "Set the audit evidence destination and operating posture.",
    choices: [
      { id: "stream-siem", label: "Stream to SIEM + review ownership", description: "Export enterprise events with named detection ownership." },
      { id: "retain-review", label: "Retain + periodic review", description: "Review within GitHub on a defined cadence." },
      { id: "on-demand", label: "On-demand investigation", description: "No continuous evidence or detection route." },
    ],
    recommended: "stream-siem",
    availability: { allOf: ["enterprise-audit", "audit-planning"] },
    rationale: "A stream only helps when a team owns intake, retention, and meaningful detection.",
    tradeoff: "Streaming adds integration and data-retention responsibilities.",
    prerequisites: "SIEM endpoint, schema ownership, and incident routing.",
    consequences: "On-demand audit review lengthens investigation and evidence collection time.",
    scope: "Enterprise",
    role: "Enterprise owner / security operations",
    applyMethod: "Audit log streaming configuration",
    influence: "Protective",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Streaming the audit log", "https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/streaming-the-audit-log-for-your-enterprise"), wa],
  },

  // --- Copilot governance ------------------------------------------------------------
  {
    id: "copilot-license-topology",
    domain: "Copilot governance",
    title: "Copilot license topology",
    prompt: "Choose who can receive seats and how exceptions are handled.",
    choices: [
      { id: "groups", label: "Team-based allocation", description: "Assign seats through accountable teams or groups." },
      { id: "self-service", label: "Managed self-service", description: "Allow requests with manager or cost-owner approval." },
      { id: "broad", label: "Broad allocation", description: "Allocate widely with later reconciliation." },
    ],
    recommended: "groups",
    availability: { anyOf: ["copilot-business", "copilot-enterprise"] },
    rationale: "A license topology connects product access to an owner, use case, and financial boundary.",
    tradeoff: "Group management requires clean team and HR lifecycle data.",
    prerequisites: "Team ownership and an intake or approval path.",
    consequences: "Broad allocation makes reclaim and cost attribution harder.",
    scope: "Enterprise or organization",
    role: "Copilot administrator",
    applyMethod: "Copilot business or enterprise settings",
    influence: "Guardrail",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Managing Copilot licenses", "https://docs.github.com/en/copilot/how-tos/administer-copilot/manage-for-enterprise/manage-access/grant-access"), copilotAdoption],
  },
  {
    id: "copilot-public-code",
    domain: "Copilot governance",
    title: "Public-code matching policy",
    prompt: "Choose the policy for suggestions matching public code.",
    choices: [
      { id: "block", label: "Block matching suggestions", description: "Favor stricter developer guidance and review." },
      { id: "allow-guidance", label: "Allow with developer guidance", description: "Pair allowance with review and attribution guidance." },
    ],
    recommended: "block",
    availability: { anyOf: ["copilot-business", "copilot-enterprise"] },
    rationale: "This is a product policy and developer workflow decision, not a universal quality score.",
    tradeoff: "Blocking can reduce suggestion availability in some contexts.",
    prerequisites: "Developer guidance and a legal or open-source policy owner.",
    consequences: "Allowing without guidance can create inconsistent review expectations.",
    scope: "Enterprise or organization",
    role: "Copilot administrator / legal policy owner",
    applyMethod: "Copilot policy settings",
    influence: "Guardrail",
    rolloutBand: "Low",
    ongoingBand: "Low",
    sources: [docs("Configuring policies", "https://docs.github.com/en/copilot/concepts/policies"), copilotAdoption],
  },
  {
    id: "copilot-content-exclusion",
    domain: "Copilot governance",
    title: "Content exclusion policy",
    prompt: "Choose the repository content boundary for Copilot.",
    choices: [
      { id: "exclude-sensitive", label: "Exclude classified repositories", description: "Maintain a reviewed exclusion inventory." },
      { id: "exclude-pilot", label: "Pilot exclusions", description: "Validate behavior with sensitive-code owners first." },
      { id: "none", label: "No exclusions", description: "Use the standard product availability boundary." },
    ],
    recommended: "exclude-sensitive",
    availability: { anyOf: ["copilot-business", "copilot-enterprise"] },
    rationale: "An exclusion policy maps product availability to an explicit repository classification decision.",
    tradeoff: "Inventory drift can leave exclusions incomplete without ownership.",
    prerequisites: "Repository classification and a review cadence.",
    consequences: "No exclusions may be inappropriate for repositories with restricted handling needs.",
    scope: "Enterprise or organization",
    role: "Copilot administrator / data owner",
    applyMethod: "Copilot content exclusion settings",
    influence: "Protective",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Excluding content", "https://docs.github.com/en/copilot/how-tos/configure-content-exclusion/exclude-content-from-copilot"), copilotAdoption],
  },
  {
    id: "copilot-model-policy",
    domain: "Copilot governance",
    title: "Model and feature policy",
    prompt: "Choose the change-management path for Copilot features.",
    choices: [
      { id: "managed-pilot", label: "Managed channel + pilot", description: "Enable approved features through a reviewable pilot." },
      { id: "managed", label: "Managed channel", description: "Central policy with standard enablement." },
      { id: "open", label: "Feature discretion", description: "Teams independently choose available features." },
    ],
    recommended: "managed-pilot",
    availability: { anyOf: ["copilot-business", "copilot-enterprise"] },
    rationale: "Features and models change; a channel provides a repeatable policy decision point.",
    tradeoff: "Managed pilots introduce review time before broad enablement.",
    prerequisites: "Feature owner, feedback route, and decision log.",
    consequences: "Open discretion fragments product policy and support expectations.",
    scope: "Enterprise or organization",
    role: "Copilot administrator",
    applyMethod: "Copilot policy settings and operating cadence",
    influence: "Guardrail",
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [docs("Configuring policies", "https://docs.github.com/en/copilot/concepts/policies"), copilotAdoption],
  },
  {
    id: "copilot-usage-metrics",
    domain: "Copilot governance",
    title: "Usage-metrics policy",
    prompt: "Set the policy for reviewing aggregated product usage.",
    choices: [
      { id: "aggregated", label: "Aggregated team metrics", description: "Use aggregate trends for adoption and support decisions." },
      { id: "minimal", label: "Minimum operational metrics", description: "Use only metrics needed for seat and support operations." },
      { id: "none", label: "No review cadence", description: "Do not establish a recurring metrics process." },
    ],
    recommended: "aggregated",
    availability: { anyOf: ["copilot-business", "copilot-enterprise"] },
    rationale: "Metrics can guide enablement and license hygiene when the purpose and audience are clear.",
    tradeoff: "Metrics need privacy-aware communication and a stated non-performance purpose.",
    prerequisites: "A written data-use policy and accountable review owner.",
    consequences: "Unclear metrics use can erode trust or leave adoption support unguided.",
    scope: "Enterprise or organization",
    role: "Copilot program owner",
    applyMethod: "Operating policy and available usage reporting",
    influence: "Enabling",
    rolloutBand: "Low",
    ongoingBand: "Moderate",
    sources: [docs("Viewing Copilot metrics", "https://docs.github.com/en/copilot/how-tos/administer-copilot/view-usage-and-adoption"), copilotAdoption],
  },

  // --- Copilot cost controls -----------------------------------------------------------
  {
    id: "cost-center-mapping",
    domain: "Copilot cost controls",
    title: "Team-to-cost-center mapping",
    prompt: "Choose the license attribution baseline.",
    choices: [
      { id: "required", label: "Required mapping before allocation", description: "Every allocation team has a cost owner." },
      { id: "wave", label: "Map in allocation waves", description: "Map funded teams first and close gaps on a schedule." },
      { id: "defer", label: "Reconcile after allocation", description: "Allocate first and resolve attribution later." },
    ],
    recommended: "required",
    availability: { anyOf: ["copilot-business", "copilot-enterprise"] },
    rationale: "Cost attribution needs a stable team, owner, and budget relationship before demand scales.",
    tradeoff: "Mapping can delay allocation for teams with incomplete finance data.",
    prerequisites: "Authoritative team ownership and cost-center data.",
    consequences: "Deferred mapping makes chargeback and reclaim disputes harder.",
    scope: "Copilot allocation groups",
    role: "Copilot program owner / finance partner",
    applyMethod: "Operating registry; automation adapter where available",
    influence: "Guardrail",
    foundational: true,
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [copilotCost, terraform],
  },
  {
    id: "cculb",
    domain: "Copilot cost controls",
    title: "Copilot included-usage budget (CCULB)",
    prompt: "Choose the included-usage budget posture by accountable group.",
    choices: [
      { id: "group-budget", label: "Group budget with owner", description: "Set reviewed budgets for mapped allocation groups." },
      { id: "enterprise-only", label: "Enterprise budget only", description: "Use a single central backstop first." },
      { id: "monitor", label: "Monitor before budgeting", description: "Observe usage while preparing budget ownership." },
    ],
    recommended: "group-budget",
    availability: { anyOf: ["copilot-business", "copilot-enterprise"] },
    rationale: "Group-level budgets make consumption conversations actionable for cost owners.",
    tradeoff: "Budget design needs clear ownership and reporting cadence.",
    prerequisites: "Cost-center mapping and a supported budget resource in the target plan.",
    consequences: "A central-only budget can mask which teams need enablement or limits.",
    scope: "Copilot allocation groups",
    role: "Finance partner / Copilot program owner",
    applyMethod: "Billing controls when available; otherwise track as an adapter dependency",
    influence: "Guardrail",
    rolloutBand: "Moderate",
    ongoingBand: "Moderate",
    sources: [copilotCost, docs("Managing budgets", "https://docs.github.com/en/billing/how-tos/set-up-budgets")],
  },
  {
    id: "included-usage-cap",
    domain: "Copilot cost controls",
    title: "Optional included-usage cap",
    prompt: "When a supported resource exists, choose the behavior at the cap.",
    choices: [
      { id: "cap-block", label: "Cap and block", description: "Stop additional included usage until the owner acts." },
      { id: "cap-overage", label: "Cap with approved overage", description: "Continue with a documented cost-owner approval." },
      { id: "no-cap", label: "No group cap", description: "Rely on the enterprise backstop and review alerts." },
    ],
    recommended: "cap-overage",
    availability: { anyOf: ["copilot-business", "copilot-enterprise"] },
    rationale: "A cap is only meaningful with a supported resource, owner, alert path, and explicit block-versus-overage choice.",
    tradeoff: "Blocking protects spend but can interrupt developer workflows; overage needs approval controls.",
    prerequisites: "Supported billing resource, cost-center mapping, alert destination, and decision owner.",
    consequences: "A cap without a response process creates surprise disruptions or unplanned spend.",
    scope: "Supported Copilot usage resource",
    role: "Finance partner / Copilot program owner",
    applyMethod: "Billing control if supported; otherwise record as a rollout dependency",
    influence: "Guardrail",
    rolloutBand: "High",
    ongoingBand: "Moderate",
    sources: [copilotCost, docs("Managing budgets", "https://docs.github.com/en/billing/how-tos/set-up-budgets")],
  },
  {
    id: "enterprise-budget-backstop",
    domain: "Copilot cost controls",
    title: "Enterprise budget backstop",
    prompt: "Set the central response when consumption approaches the enterprise boundary.",
    choices: [
      { id: "alerts-approval", label: "Alerts + finance approval", description: "Notify owners and require approval for material changes." },
      { id: "alerts", label: "Alerts only", description: "Central team observes without a defined approval gate." },
      { id: "none", label: "No enterprise backstop", description: "Rely on group practices only." },
    ],
    recommended: "alerts-approval",
    availability: { anyOf: ["copilot-business", "copilot-enterprise"] },
    rationale: "A central backstop catches aggregation risk that team-level views can miss.",
    tradeoff: "Central control needs timely finance and program-owner response.",
    prerequisites: "Enterprise budget owner, alert route, and review cadence.",
    consequences: "No backstop can make cumulative consumption visible too late for planned response.",
    scope: "Enterprise billing",
    role: "Enterprise billing manager / finance partner",
    applyMethod: "Enterprise billing settings and operating cadence",
    influence: "Protective",
    foundational: true,
    rolloutBand: "Low",
    ongoingBand: "Moderate",
    sources: [copilotCost, docs("Managing budgets", "https://docs.github.com/en/billing/how-tos/set-up-budgets")],
  },
]
